from pathlib import Path
import json
import re

from Bio import Phylo


# ---------------------------------------------------------
# Paths
# ---------------------------------------------------------

ROOT_DIR = Path(__file__).resolve().parents[1]

INPUT_FILE = (
    ROOT_DIR
    / "data"
    / "raw"
    / "opentree"
    / "primates.newick"
)

OUTPUT_DIR = (
    ROOT_DIR
    / "data"
    / "processed"
    / "opentree"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

OUTPUT_FILE = (
    OUTPUT_DIR
    / "primates.nodes.json"
)


# ---------------------------------------------------------
# OpenTree label parsing
# ---------------------------------------------------------

# OpenTree labels using name_and_id generally look like:
#
# Homo_sapiens_ott770315
#
# or:
#
# Primates_ott913935
#
# The expression separates the taxon name from the OTT ID.
OTT_PATTERN = re.compile(
    r"^(.*)[_ ]ott(\d+)$"
)


def parse_label(label: str | None):
    """
    Convert an OpenTree Newick label into:

        scientific_name
        ott_id

    Example:

        Homo_sapiens_ott770315

    becomes:

        Homo sapiens
        770315

    Some synthetic internal nodes have no taxonomic
    name or OTT ID. Those are handled separately.
    """

    if not label:
        return None, None

    match = OTT_PATTERN.match(label)

    if not match:
        return (
            label.replace("_", " "),
            None,
        )

    scientific_name = (
        match.group(1)
        .replace("_", " ")
    )

    ott_id = int(
        match.group(2)
    )

    return (
        scientific_name,
        ott_id,
    )


# ---------------------------------------------------------
# Load Newick tree
# ---------------------------------------------------------

if not INPUT_FILE.exists():
    raise FileNotFoundError(
        f"Input file does not exist: {INPUT_FILE}"
    )


print()
print("Reading OpenTree Primates Newick tree...")

tree = Phylo.read(
    INPUT_FILE,
    "newick",
)


# ---------------------------------------------------------
# Convert tree into our node format
# ---------------------------------------------------------

nodes = []

generated_id = 0


def walk(
    clade,
    parent_id=None,
    depth=0,
):
    """
    Recursively traverse the OpenTree phylogeny
    and convert every clade/taxon into a flat node.

    The output structure is intentionally simple:

        id
        parentId
        scientificName
        ottId
        depth
        isTerminal
        isSyntheticNode

    This will become the data contract used by
    our visualization pipeline.
    """

    global generated_id

    scientific_name, ott_id = (
        parse_label(
            clade.name
        )
    )


    # Named OpenTree taxa use their OTT identifier.
    #
    # Unnamed structural nodes receive a temporary
    # internal ID that is unique within this export.
    if ott_id is not None:

        node_id = (
            f"ott{ott_id}"
        )

        is_synthetic_node = False

    else:

        generated_id += 1

        node_id = (
            f"internal-{generated_id}"
        )

        is_synthetic_node = True


    # Unnamed nodes are genuine structural branching
    # points in the synthetic phylogeny, so retain
    # them rather than throwing them away.
    display_name = (
        scientific_name
        if scientific_name
        else "Unnamed clade"
    )


    node = {
        "id": node_id,

        "parentId": parent_id,

        "scientificName": display_name,

        "ottId": ott_id,

        "depth": depth,

        # Terminal means:
        #
        # "This node has no children in this
        # particular synthetic tree."
        #
        # It does NOT necessarily mean "species."
        "isTerminal": (
            clade.is_terminal()
        ),

        # True for unnamed structural branching
        # points generated by the synthetic tree.
        "isSyntheticNode": (
            is_synthetic_node
        ),
    }


    nodes.append(node)


    # Recursively process children.
    for child in clade.clades:

        walk(
            child,
            parent_id=node_id,
            depth=depth + 1,
        )


walk(tree.root)


# ---------------------------------------------------------
# Validate basic tree structure
# ---------------------------------------------------------

root_nodes = [
    node
    for node in nodes
    if node["parentId"] is None
]


if len(root_nodes) != 1:
    raise RuntimeError(
        "Expected exactly one root node, "
        f"but found {len(root_nodes)}."
    )


node_ids = {
    node["id"]
    for node in nodes
}


if len(node_ids) != len(nodes):
    raise RuntimeError(
        "Duplicate node IDs detected."
    )


for node in nodes:

    parent_id = node["parentId"]

    if (
        parent_id is not None
        and parent_id not in node_ids
    ):
        raise RuntimeError(
            "Node references missing parent: "
            f"{node['id']} -> {parent_id}"
        )


# ---------------------------------------------------------
# Write processed JSON
# ---------------------------------------------------------

with OUTPUT_FILE.open(
    "w",
    encoding="utf-8",
) as file:

    json.dump(
        nodes,
        file,
        indent=2,
        ensure_ascii=False,
    )

# Vite serves this directory in development and copies it into production.
# Keep the intermediate export and the browser dataset in sync on every run.
PUBLIC_FILE = ROOT_DIR / "public" / "data" / "primates.nodes.json"
PUBLIC_FILE.parent.mkdir(parents=True, exist_ok=True)
PUBLIC_FILE.write_text(OUTPUT_FILE.read_text(encoding="utf-8"), encoding="utf-8")


# ---------------------------------------------------------
# Summary statistics
# ---------------------------------------------------------

terminal_count = sum(
    node["isTerminal"]
    for node in nodes
)

internal_count = (
    len(nodes)
    - terminal_count
)

synthetic_count = sum(
    node["isSyntheticNode"]
    for node in nodes
)

named_taxon_count = (
    len(nodes)
    - synthetic_count
)

max_depth = max(
    node["depth"]
    for node in nodes
)

root = root_nodes[0]


# ---------------------------------------------------------
# Output
# ---------------------------------------------------------

print()
print(
    "OpenTree Primates processed successfully."
)

print()

print(
    f"Root:             "
    f"{root['scientificName']} "
    f"({root['id']})"
)

print()

print(
    f"Total nodes:      "
    f"{len(nodes):,}"
)

print(
    f"Named taxa:       "
    f"{named_taxon_count:,}"
)

print(
    f"Synthetic nodes:  "
    f"{synthetic_count:,}"
)

print(
    f"Terminal nodes:   "
    f"{terminal_count:,}"
)

print(
    f"Internal nodes:   "
    f"{internal_count:,}"
)

print(
    f"Maximum depth:    "
    f"{max_depth:,}"
)

print()

print("Output:")
print(OUTPUT_FILE)
print(PUBLIC_FILE)
print()
